export const fake_student = {
  first_name: 'John',
  last_name: 'Doe',
  email: 'jaydang@berkeley.edu',
  phone: '1234567890',
  desired_location: ['San Francisco', 'Los Angeles'],
  desired_roles: ['Software Engineer', 'Product Manager'],
  desired_work_type: 'Internship',
  desired_duration: '6 months',
  desired_start_date: '2020-01-01',
  accept_unpaid: true,
  accept_parttime: true,
  parttime_hours: 20,
  clubExperienceIDs: ['1', '2'],
  workExperienceIDs: ['1', '2'],
  researchExperienceIDs: ['1', '2'],
  HonorsIDs: ['1', '2'],
  skills: ['Java', 'Python', 'C++'],
  caseDemoIDs: ['1', '2'],
  self_intro: 'I am a student at UC Berkeley',
  resume: 'https://www.google.com',
  educationIDs: ['1', '2'],
  id: '1'
};
